// This file is automatically generated. Do not edit.
/* eslint-disable */
import { FirebaseOptions } from "firebase/app";

export const firebaseConfig: FirebaseOptions = {
  "projectId": "studio-8911058097-8d72f",
  "appId": "1:807177061596:web:e6b29126d6c52e576ce019",
  "apiKey": "AIzaSyAVBx3OVYl8SZSfjW23WIyV7o42JUcFAtk",
  "authDomain": "studio-8911058097-8d72f.firebaseapp.com",
  "measurementId": "",
  "storageBucket": "studio-8911058097-8d72f.firebasestorage.app",
  "messagingSenderId": "807177061596"
};
